before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq gcc g++ build-essential libkyotocabinet-dev
    - sudo apt-get install -qq python3
    - sudo pip install virtualenv
    - sudo pip install coveralls
    - virtualenv venv
    - venv/bin/pip install -r requirements.txt
python:
    - 2.7
script:
    - coverage run ok-serve --test
after_success:
    - coveralls
