before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq gcc g++ build-essential libkyotocabinet-dev
    - sudo apt-get install -qq python3
    - sudo python setup.py install
python:
    - 2.7
script:
    - ./ok-serve -t
