install:
    - sudo apt-get install -qq gcc build-essential libkyotocabinet-dev
python:
    - 2.7
before_script:
    - sudo pip install virtualenv
    - virtualenv venv
    - venv/bin/pip install -r requirements.txt
script:
    - ./ok-serve -t
